version: '3'
services:
  packet_purchaser:
    build:
      context: .
      dockerfile: Dockerfile-local
    image:  quay.io/team-helium/packet_purchaser:local
    container_name: helium_packet_purchaser
    restart: always
    env_file: .env
    network_mode: host
    volumes:
      - /var/data:/var/data
      - ./routing_config.json:/var/data/routing_config.json
