version: '3'
services:
  packet_purchaser:
    image: quay.io/team-helium/packet_purchaser:latest
    container_name: helium_packet_purchaser
    restart: always
    env_file: .env
    network_mode: host
    volumes:
      - /var/data:/var/data
  prometheus:
    image: prom/prometheus
    container_name: helium_prometheus
    network_mode: host
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: helium_node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
