global:
  scrape_interval: 10s
  evaluation_interval: 10s
  external_labels:
    server: local-packet-purchser

scrape_configs:
  - job_name: packet_purchaser
    static_configs:
      - targets: ['localhost:3000']
